server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 43.143.170.155:8848
        #        server-addr: 127.0.0.1:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        namespace: dev
        register-enabled: true
        username: nacos
        password: nacos
    gateway:
      routes:
#        - id: user-service
#          predicates:
#            - Path=/users/**
##            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#          uri: http://localhost:8081
##          filters:
##            - AddRequestHeader=X-Request-red, blue
##        - id: content-service
##          predicates:
##            - Path=/share/**
##          uri: http://localhost:8082
#        - id: notice-service
#          filters:
#            - CircuitBreaker=myCircuitBreaker
#          predicates:
#            - Path=/notice/**
#          uri: http://localhost:8083



