server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 43.143.170.155:8848
        #        server-addr: 127.0.0.1:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        namespace: pro
        register-enabled: true
        username: nacos
        password: nacos
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          predicates:
#            - Path=/users/**
#          uri: http://localhost:8081
#        - id: content-service
#          predicates:
#            - Path=/share/**
#          uri: http://localhost:8082
#        - id: notice-service
#          predicates:
#            - Path=/notice/**
#          uri: http://localhost:8083


