server:
  port: 8085
minio:
  endPoint: http://43.143.170.155:9000
  accessKey: admin
  secretKey: admin123

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 43.143.170.155:8848
        #        server-addr: 127.0.0.1:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        namespace: dev
        register-enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
      file-size-threshold: 500MB
